version: 2
updates:
  - package-ecosystem: "npm" # or yarn, pip, docker, etc.
    directory: "/" # Directory where the package.json or other dependency files are located
    schedule:
      interval: "daily" # Schedule for checking updates (daily, weekly, monthly)
    ignore:
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
