// =============================
// DisclaimerModal.tsx
// Modal showing the full disclaimer text, triggered from a small link on the
// landing page instead of always-visible text (saves vertical space on mobile).
// =============================

import React from "react";
import styles from "./styles/BotCreator.module.css";
import DisclaimerStyleModal from "./DisclaimerStyleModal";

interface DisclaimerModalProps {
  show: boolean;
  onClose: () => void;
}

const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ show, onClose }) => (
  <DisclaimerStyleModal
    show={show}
    onClose={onClose}
    title="Disclaimer"
    closeLabel="Close disclaimer"
    testId="disclaimer-modal-backdrop"
  >
    <p className={styles.disclaimerText}>
      This chatbot is for entertainment purposes only. No information provided
      should be considered professional, legal, medical, or financial advice.
      Content may be generated by artificial intelligence and may contain
      inaccuracies or limitations. Use at your own risk. The creators disclaim
      all liability for actions taken based on chatbot interactions.
    </p>
  </DisclaimerStyleModal>
);

export default DisclaimerModal;
