// =============================
// DisclaimerModal.tsx
// Modal showing the full disclaimer text, triggered from a small link on the
// landing page instead of always-visible text (saves vertical space on mobile).
// =============================

import React from "react";
import styles from "./styles/BotCreator.module.css";

interface DisclaimerModalProps {
  show: boolean;
  onClose: () => void;
}

const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ show, onClose }) => {
  if (!show) return null;
  return (
    <div className={styles.disclaimerBackdrop} data-testid="disclaimer-modal-backdrop" onClick={onClose}>
      <div className={styles.disclaimerModal} onClick={e => e.stopPropagation()}>
        <button
          className={styles.disclaimerCloseButton}
          aria-label="Close disclaimer"
          onClick={onClose}
        >
          ×
        </button>
        <div className={styles.disclaimerTitle}>Disclaimer</div>
        <p className={styles.disclaimerText}>
          This chatbot is for entertainment purposes only. No information provided
          should be considered professional, legal, medical, or financial advice.
          Content may be generated by artificial intelligence and may contain
          inaccuracies or limitations. Use at your own risk. The creators disclaim
          all liability for actions taken based on chatbot interactions.
        </p>
      </div>
    </div>
  );
};

export default DisclaimerModal;
