/**
 * Brand color/font tokens and copy shared between the web app and the mobile
 * client. The colors are authored once, in Style Dictionary token format, under
 * `src/tokens/{light,dark}.json` — the same files `scripts/generate-theme-css.cjs`
 * (repo root) feeds to Style Dictionary to produce
 * `app/theme-tokens.generated.css` for the web app. This file just flattens those
 * same token files into the plain objects the mobile app (which has no CSS
 * custom-properties mechanism) can read directly. Fonts live in `src/tokens/fonts.json`
 * instead — see that file's own description for why they aren't Style Dictionary
 * tokens too. Edit color/font values only in `src/tokens/`, never here.
 */
import lightTokens from "./tokens/light.json";
import darkTokens from "./tokens/dark.json";
import fontTokens from "./tokens/fonts.json";

type TokenLeaf = { value: string };
type TokenTree = Record<string, Record<string, TokenLeaf>>;

/** Flattens a Style Dictionary token file (`{color: {background: {value}}, disabled: {bg: {value}}, ...}`)
 * into the single flat color object both apps consume. Builds the result with explicit
 * assignment rather than an object spread of `Object.fromEntries(...)` — TypeScript drops
 * that call's index signature when it's spread into an object literal, which silently
 * narrowed the inferred return type to just the four disabled/scrollbar keys. */
function flatten(tree: TokenTree): Record<string, string> {
  const { color, disabled, scrollbar } = tree;
  const result: Record<string, string> = {};
  for (const [key, { value }] of Object.entries(color)) {
    result[key] = value;
  }
  result.disabledBg = disabled.bg.value;
  result.disabledText = disabled.text.value;
  result.scrollbarBg = scrollbar.bg.value;
  result.scrollbarThumb = scrollbar.thumb.value;
  return result;
}

/** Light-mode palette — "Museum Placard": sepia ink and patina-green on parchment. */
export const lightColors = flatten(lightTokens as TokenTree);

/** Dark-mode palette — the same archive, lit from a darkroom rather than a window. */
export const darkColors = flatten(darkTokens as TokenTree);

export type ThemeColors = typeof lightColors;

/**
 * Font family tokens shared with the web app's generated CSS. Mobile has no bundled
 * Google Fonts loader yet, so `apps/mobile`'s own components still fall back to the
 * platform serif (see Wordmark.tsx) rather than loading `fonts.primary.family`
 * itself — these values exist so that adding real font loading later is a
 * mobile-side change only, not another round of picking fonts.
 */
export const fonts = fontTokens;

/**
 * Whether the app defaults to dark mode for a visitor/device with no stored
 * preference yet (an explicit toggle choice always overrides this on return visits).
 * The one place to change this going forward — mobile's ThemeContext.tsx imports it
 * directly; the web app keeps its own local equivalent in DarkModeContext.tsx (see
 * that file's own doc comment for why it isn't imported from here too) but both
 * should be kept in sync by eye if this value ever changes.
 */
export const DEFAULT_DARK_MODE = true;

/** In-app wordmark/hero copy — mirrors BotCreator.tsx's hero section exactly. */
export const BRAND = {
  name: "Portrayal",
  kicker: "Begin a conversation",
  headline: "Who will you bring to life?",
  /** Small badge shown next to the wordmark while the app is in beta. */
  betaLabel: "Beta",
  /**
   * Full disclaimer text, shown behind a "Disclaimer" footer link on both
   * platforms (web: DisclaimerModal.tsx, mobile: DisclaimerModal.tsx) rather
   * than always-visible — added 2026-09-23 at the user's request to call out
   * both the app's beta status and its existing AI-generated-content caveat
   * in one place, kept here so the wording can't drift between platforms.
   */
  disclaimer:
    "This app is in early beta: expect bugs and rough edges. It's for entertainment purposes only. No information provided should be considered professional, legal, medical, or financial advice. Content may be generated by artificial intelligence and may contain inaccuracies or limitations. Use at your own risk. The creators disclaim all liability for actions taken based on chatbot interactions.",
} as const;
