/**
 * Brand color tokens and copy shared between the web app (app/globals.css,
 * app/darkmode.css) and the mobile client (which has no CSS custom-properties
 * mechanism, so these need to exist as plain JS values somewhere both can read).
 * The web app still hand-maintains its own CSS copies of these — see
 * character-chatbot-mobile/CLAUDE.md's "production web app has NOT been migrated"
 * note — so keep the two in sync by eye until/unless the web app migrates to
 * import from here directly.
 */

/** Light-mode palette — mirrors app/globals.css's `:root` block. */
export const lightColors = {
  background: "#f7f4ef",
  surface: "#ffffff",
  surfaceVariant: "#f1ddd3",
  outline: "#9c8f7d",
  text: "#18160f",
  textSecondary: "#5c5245",
  primary: "#af5a3f",
  onPrimary: "#ffffff",
  primaryContainer: "#f1ddd3",
  secondary: "#33595e",
  onSecondary: "#ffffff",
  secondaryContainer: "#dbe7e6",
  accent: "#3d6e73",
  error: "#8b3a3a",
  errorContainer: "#f2ddd8",
  warning: "#b8863f",
} as const;

/** Dark-mode palette — mirrors app/darkmode.css's `.dark` block. */
export const darkColors = {
  background: "#151209",
  surface: "#211d15",
  surfaceVariant: "#2c2620",
  outline: "#9c8f7d",
  text: "#f5f1ea",
  textSecondary: "#bcae9a",
  primary: "#d68a6c",
  onPrimary: "#18160f",
  primaryContainer: "#8a4630",
  secondary: "#7bb0b5",
  onSecondary: "#12211f",
  secondaryContainer: "#2c5257",
  accent: "#8fc4c8",
  error: "#c97a72",
  errorContainer: "#6b2f2f",
  warning: "#dab06a",
} as const;

export type ThemeColors = Record<keyof typeof lightColors, string>;

/**
 * Whether the app defaults to dark mode for a visitor/device with no stored
 * preference yet (an explicit toggle choice always overrides this on return visits).
 * The one place to change this going forward — mobile's ThemeContext.tsx imports it
 * directly; the web app keeps its own local equivalent in DarkModeContext.tsx (see
 * that file's own doc comment for why it isn't imported from here too) but both
 * should be kept in sync by eye if this value ever changes.
 */
export const DEFAULT_DARK_MODE = true;

/** In-app wordmark/hero copy — mirrors BotCreator.tsx's hero section exactly. */
export const BRAND = {
  name: "Portrayal",
  kicker: "Begin a conversation",
  headline: "Who will you bring to life?",
  /** Small badge shown next to the wordmark while the app is in beta. */
  betaLabel: "Beta",
  /**
   * Full disclaimer text, shown behind a "Disclaimer" footer link on both
   * platforms (web: DisclaimerModal.tsx, mobile: DisclaimerModal.tsx) rather
   * than always-visible — added 2026-09-23 at the user's request to call out
   * both the app's beta status and its existing AI-generated-content caveat
   * in one place, kept here so the wording can't drift between platforms.
   */
  disclaimer:
    "This app is in early beta: expect bugs and rough edges. It's for entertainment purposes only. No information provided should be considered professional, legal, medical, or financial advice. Content may be generated by artificial intelligence and may contain inaccuracies or limitations. Use at your own risk. The creators disclaim all liability for actions taken based on chatbot interactions.",
} as const;
