# This workflow automatically enables auto-merge for pull requests created by Dependabot.
# It uses the peter-evans/enable-pull-request-automerge GitHub Action.
#
# How it works:
# - Triggers on pull requests that are opened, reopened, or synchronized.
# - Only runs if the PR author is dependabot[bot].
# - Grants write permissions to pull requests and repository contents.
# - Uses the action to enable auto-merge with the default merge method.
# - The PR will be merged automatically after all required status checks (as defined in branch protection rules) pass.

name: Enable auto-merge for Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          pull-request-number: ${{ github.event.pull_request.number }}
