name: Auto-approve and merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve-and-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Debug: Echo token length (should not be 0)"
        run: 'echo "Token length: $(echo -n $GH_TOKEN | wc -c)"'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check gh CLI version
        run: gh --version

      - name: Check gh auth status
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

# NOTE: The PERSONAL_ACCESS_TOKEN secret must be set in your repo with 'repo' (classic) or 'Contents: Read and write' and 'Pull requests: Read and write' (fine-grained) permissions.
