name: Secret scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lightweight secret scanner
        run: |
          chmod +x scripts/scan-secrets.sh
          scripts/scan-secrets.sh
