name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run secret scan
        run: |
          echo "Scanning for secrets..."
          ./scripts/scan-secrets.sh

